### ISSUE TITLE
material-theme-builderによるサイト配色の試行錯誤

### ISSUE THREAD

**Issue by varmil** [varmil/noxi#1431]
https://material-foundation.github.io/material-theme-builder/

root（ライトモードのみ）試作した

```css
@import 'tailwindcss';

@plugin 'tailwindcss-animate';
@plugin '@tailwindcss/container-queries';

@custom-variant dark (&:is(.dark *));

@theme inline {
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-background: var(--background);
  --color-foreground: var(--foreground);

  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-primary-container: var(--primary-container);
  --color-on-primary-container: var(--on-primary-container);

  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-secondary-container: var(--secondary-container);
  --color-on-secondary-container: var(--on-secondary-container);

  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);

  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);

  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);

  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);

  --color-surface-container: var(--surface-container);
  --color-on-surface: var(--on-surface);

  --radius-lg: var(--radius);
  --radius-md: calc(var(--radius) - 2px);
  --radius-sm: calc(var(--radius) - 4px);

  --color-gold: var(--gold);
  --color-silver: var(--silver);
  --color-bronze: var(--bronze);

  --animate-wiggle: wiggle 1s ease-in-out infinite;
  --animate-accordion-down: accordion-down 0.2s ease-out;
  --animate-accordion-up: accordion-up 0.2s ease-out;

  @keyframes accordion-down {
    from {
      height: 0;
    }
    to {
      height: var(--radix-accordion-content-height);
    }
  }
  @keyframes accordion-up {
    from {
      height: var(--radix-accordion-content-height);
    }
    to {
      height: 0;
    }
  }

  @keyframes wiggle {
    0%,
    100% {
      transform: rotate(-3deg);
    }
    50% {
      transform: rotate(3deg);
    }
  }
}

@utility container {
  margin-inline: auto;
  padding-inline: 2rem;
  @media (width >= --theme(--breakpoint-sm)) {
    max-width: none;
  }
  @media (width >= 1400px) {
    max-width: 1400px;
  }
}

/*
  The default border color has changed to `currentColor` in Tailwind CSS v4,
  so we've added these compatibility styles to make sure everything still
  looks the same as it did with Tailwind CSS v3.

  If we ever want to remove these styles, we need to add an explicit border
  color utility to any element that depends on these defaults.
*/
@layer base {
  *,
  ::after,
  ::before,
  ::backdrop,
  ::file-selector-button {
    border-color: var(--color-gray-200, currentColor);
  }
}

@utility content-visibility-auto {
  content-visibility: auto;
}

@utility content-visibility-hidden {
  content-visibility: hidden;
}

@utility content-visibility-visible {
  content-visibility: visible;
}

@layer base {
  :root {
    --background: rgb(255 248 246);
    --foreground: rgb(35 25 23);
    --surface-container: rgb(255 240 238);
    --on-surface: rgb(35 25 23);
    --popover: rgb(252 234 230);
    --primary: rgb(144 75 60);
    --popover-foreground: rgb(35 25 23);
    --primary-container: rgb(255 218 211);
    --on-primary-container: rgb(115 52 39);
    --primary-foreground: rgb(255 255 255);
    --secondary: rgb(119 87 80);
    --secondary-foreground: rgb(255 255 255);
    --secondary-container: rgb(255 218 211);
    --on-secondary-container: rgb(93 63 57);
    --muted: rgb(245 221 217);
    --muted-foreground: rgb(83 67 64);
    --accent: rgb(110 93 46);
    --accent-foreground: rgb(255 255 255);
    --destructive: rgb(186 26 26);
    --destructive-foreground: rgb(255 255 255);
    --border: rgb(227 215 212);
    --input: rgb(227 215 212);
    --ring: rgb(144 75 60);
    --radius: 0.5rem;

    --chart-1: hsl(12, 76%, 61%);
    --chart-2: hsl(173, 58%, 39%);
    --chart-3: hsl(197, 37%, 24%);
    --chart-4: hsl(43, 74%, 66%);
    --chart-5: hsl(27, 87%, 67%);

    --gold: hsl(51, 100%, 50%);
    --silver: hsl(0, 0%, 75%);
    --bronze: hsl(30, 60%, 50%);
  }

  .dark {
    --background: hsl(240, 10%, 3.9%);
    --foreground: hsl(0, 0%, 98%);
    --card: hsl(240, 10%, 3.9%);
    --card-foreground: hsl(0, 0%, 98%);
    --popover: hsl(240, 10%, 3.9%);
    --popover-foreground: hsl(0, 0%, 98%);
    --primary: hsl(0, 0%, 98%);
    --primary-foreground: hsl(240, 5.9%, 10%);
    --secondary: hsl(240, 3.7%, 15.9%);
    --secondary-foreground: hsl(0, 0%, 98%);
    --muted: hsl(240, 3.7%, 15.9%);
    --muted-foreground: hsl(240, 5%, 64.9%);
    --accent: hsl(240, 3.7%, 15.9%);
    --accent-foreground: hsl(0, 0%, 98%);
    --destructive: hsl(0, 62.8%, 30.6%);
    --destructive-foreground: hsl(0, 0%, 98%);
    --border: hsl(240, 3.7%, 15.9%);
    --input: hsl(240, 3.7%, 15.9%);
    --ring: hsl(240, 4.9%, 83.9%);
    --chart-1: hsl(220, 70%, 50%);
    --chart-2: hsl(160, 60%, 45%);
    --chart-3: hsl(30, 80%, 55%);
    --chart-4: hsl(280, 65%, 60%);
    --chart-5: hsl(340, 75%, 55%);
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}

@supports not (overflow-wrap: anywhere) {
  .break-anywhere {
    word-break: break-word;
  }
}
@supports (overflow-wrap: anywhere) {
  .break-anywhere {
    overflow-wrap: anywhere;
  }
}
```
